version: '3.8'

services:
  neo4j:
    image: neo4j:5.26.5
    container_name: neo4j-db
    ports:
      - "7474:7474"  # HTTP port untuk Neo4j browser
      - "7687:7687"  # Bolt port untuk koneksi
    environment:
      - NEO4J_AUTH=neo4j/alfien0310
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-import:/import
    networks:
      - temupaper-app-network

  django-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: django-app
    ports:
      - "8000:8000"
    depends_on:
      - neo4j
    environment:
      - DJANGO_SETTINGS_MODULE=temupaper_app.settings
      - NEO4J_URI=bolt://neo4j-db:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=
    volumes:
      - .:/app
    networks: 
      - temupaper-app-network

networks:
  temupaper-app-network:
    driver: bridge

volumes:
  neo4j-data:
  neo4j-logs:
  neo4j-import:
